# Generated by Django 3.1.4 on 2021-01-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='body_in_arabic',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='title_in_arabic',
        ),
    ]
