# Generated by Django 3.1.4 on 2020-12-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_contactus_payment_privacypolicy_settings_termsandcondition_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_coins', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
