# Generated by Django 3.1.4 on 2020-12-24 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
