# Generated by Django 3.1.4 on 2020-12-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_coin_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='created_at',
        ),
    ]
