# Generated by Django 3.1.4 on 2020-12-24 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_coin_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
