# Generated by Django 3.1.4 on 2021-01-20 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='date_read',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appnotification',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 6, 48, 0, 197554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
