# Generated by Django 3.1.4 on 2021-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_hitinaday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='device_token',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
