# Generated by Django 3.1.4 on 2021-01-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='goku.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to='src.appuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
    ]
