# Generated by Django 3.1.4 on 2021-01-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20210106_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateField()),
                ('mode', models.CharField(default='', max_length=100)),
                ('sent_to', models.ManyToManyField(related_name='sent_to', to='src.AppUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
    ]
