# Generated by Django 3.1.4 on 2021-01-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20210122_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.message'),
        ),
    ]
