# Generated by Django 3.1.4 on 2021-01-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20210106_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.message'),
            preserve_default=False,
        ),
    ]
