# Generated by Django 3.1.4 on 2021-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20210122_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='sent_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='sent_to', to='src.AppUser'),
        ),
    ]
