# Generated by Django 3.1.4 on 2021-01-22 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20210122_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 22, 7, 2, 0, 156582, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='sent_to',
            field=models.ManyToManyField(related_name='sent_to', to='src.AppUser'),
        ),
    ]
