# Generated by Django 3.1.4 on 2021-01-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_appnotification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ques_attachment',
        ),
    ]
