# Generated by Django 3.1.4 on 2021-01-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_message_ques_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
