# Generated by Django 3.1.4 on 2021-01-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_appnotification_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnotification',
            name='on',
        ),
        migrations.CreateModel(
            name='AppNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
    ]
