# Generated by Django 3.1.4 on 2021-02-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnRegisteredMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.message')),
            ],
        ),
    ]
