# Generated by Django 3.1.4 on 2021-01-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20210118_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
