# Generated by Django 3.1.4 on 2021-01-20 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_appnotification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='mode',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Everybody', 'Everybody'), ('Race', 'Race')], default='', max_length=100),
        ),
    ]
