# Generated by Django 3.1.4 on 2021-01-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20210120_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
