# Generated by Django 3.1.2 on 2021-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20210316_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
