# Generated by Django 3.1.2 on 2021-03-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20210316_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='device_type',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.appuser'),
        ),
    ]
